import React, { createContext, useContext, useState, useEffect } from "react";

export const LANGUAGES = [
  { code: "en", name: "English", flag: "🇺🇸", native: "English" },
  { code: "es", name: "Spanish", flag: "🇪🇸", native: "Español" },
  { code: "fr", name: "French", flag: "🇫🇷", native: "Français" },
  { code: "de", name: "German", flag: "🇩🇪", native: "Deutsch" },
  { code: "it", name: "Italian", flag: "🇮🇹", native: "Italiano" },
  { code: "hi", name: "Hindi", flag: "🇮🇳", native: "हिन्दी" },
  { code: "ja", name: "Japanese", flag: "🇯🇵", native: "日本語" },
];

const TRANSLATIONS = {
  en: {
    nav: {
      game: "Play Game",
      features: "Features",
      blog: "Blog",
      faq: "FAQ",
      history: "History",
      language: "Language",
      login: "Log In",
      signup: "Sign Up",
      logout: "Log Out",
      welcome: "Welcome back",
    },
    game: {
      srTitle: "Heads or Tails — Online Coin Flip Game",
      heads: "Heads",
      tails: "Tails",
      flipBtn: "Flip the coin",
      flippingBtn: "Flipping…",
      statusFlipping: "Flipping…",
      statusPrompt: "Pick a side and flip.",
      statusWonSuffix: "— you called it right! 🎉",
      statusLostSuffix: "— better luck next flip.",
      flippingCaption: "Flipping the {name} coin",
      soundMuted: "Muted",
      soundOn: "Sound On",
      soundMuteAria: "Mute sound effects",
      soundUnmuteAria: "Unmute sound effects",
      offlineNote: "Playing offline — scores are saved on this device only.",
      howItWorksTitle: "How the coin flip game works",
      howItWorksText:
        "Choose heads or tails, pick a coin design, then flip. Each result comes from a fair, independent 50/50 random draw — computed server-side with cryptographic security when you're online. Your streak, win rate, and last 20 flips are tracked automatically.",
    },
    scoreboard: {
      flips: "Flips",
      wins: "Wins",
      losses: "Losses",
      winRate: "Win rate",
      bestStreak: "Best streak",
    },
    history: {
      title: "Recent flips",
      empty: "Your flips will show up here — call it in the air and go.",
      guestPrompt: "Sign in to record your streaks, customize coins, and view your Recent Flips history.",
      winBadge: "WIN",
      lossBadge: "LOSS",
      called: "Called",
      landed: "Landed",
    },
    coins: {
      quarter: "US Quarter",
      uk10p: "UK 10 Pence",
      rupee: "Indian Rupee",
      dirham: "UAE Dirham",
      penny: "US Penny",
    },
    blog: {
      backToGame: "Back to Coin Flip",
      title: "Coin Flip Insights & Articles",
      subtitle: "Probability theory, decision making strategies, and the rich history of coin tosses.",
      readTime: "min read",
      takeaway: "Key Takeaway",
      article1Tag: "Mathematics & Probability",
      article1Title: "Is a Coin Toss Truly 50/50? The Science Behind the Spin",
      article1P1: "For centuries, humanity has resolved disputes, awarded ball possession in championships, and made life-altering decisions with the simple flick of a coin. But mathematically speaking, is an airborne coin toss exactly 50.000% fair?",
      article1P2: "In a landmark Stanford University study by mathematicians Persi Diaconis, Susan Holmes, and Richard Montgomery, high-speed cameras revealed that physical coin tosses have a slight 50.8% bias toward landing on the same face that started facing upward.",
      article1P3: "In our digital coin flip engine, we eliminate physical bias entirely. Every toss is computed with cryptographically secure random number generation (CSPRNG), ensuring mathematically pure 50/50 odds.",
      article1Takeaway: "While physical coins experience tiny micro-biases from initial rotational wobble, our digital CSPRNG flips provide mathematically pure 50.000% odds.",
      article2Tag: "Psychology & Decision Making",
      article2Title: "Decision Fatigue? Why Smart Leaders Use Coin Flips",
      article2P1: "According to modern behavioral psychology, the average adult makes roughly 35,000 conscious decisions every single day. This causes decision fatigue — leading to procrastination and mental exhaustion.",
      article2P2: "Renowned Danish polymath Piet Hein famously advocated the coin flip technique: not because the coin makes the decision for you, but because in the brief split-second while the coin is in the air, your subconscious mind suddenly realizes which outcome you are secretly hoping for.",
      article2P3: "Next time you are stuck between two equally viable paths, flip a coin. Notice how you feel about the result before acting — it immediately cuts through cognitive gridlock.",
      article2Takeaway: "The real power of a coin flip is revealing your true subconscious preference during the moments the coin is spinning in the air.",
      article3Tag: "History & Culture",
      article3Title: "From Julius Caesar to Super Bowl Sunday: The Rich History of Heads or Tails",
      article3P1: "The custom of tossing a coin dates back thousands of years. In Ancient Rome, the game was known as 'Navia aut Caput' (Ship or Head), referencing coins that bore the Emperor’s head on the obverse and a naval ship prow on the reverse.",
      article3P2: "Romans treated the coin toss as an appeal to divine justice; in legal disputes with deadlocked evidence, magistrates would flip a coin bearing Caesar's profile, believing the Emperor’s spirit would guide the outcome toward truth.",
      article3P3: "Today, the tradition lives on at the grandest stages of modern sports — from cricket match tosses determining batting order to the prestigious NFL Super Bowl opening coin flip watched by over 120 million fans worldwide.",
      article3Takeaway: "For over 2,000 years, civilizations have used the coin flip as an impartial arbiter of chance, honor, and destiny.",
    },
    faq: {
      title: "Frequently Asked Questions",
      subtitle: "Everything you need to know about coin flip probability, cryptographic fairness, account features, and history.",
      backToGame: "Back to Coin Flip",
      q1: "Is this coin flip truly fair and 50/50 unbiased?",
      a1: "Yes! Unlike a simple Math.random() script, our server engine utilizes cryptographically secure pseudorandomness (CSPRNG via Node.js crypto API), ensuring true, unbiased 50.000% odds on every single turn.",
      q2: "How does MongoDB Atlas store my stats and account?",
      a2: "When you sign up or log in, your flip records, win/loss stats, and best streaks are securely stored in MongoDB Atlas cloud. Your password is encrypted with bcryptjs and tokens use JWT.",
      q3: "Why did a Stanford study find that physical coin tosses have a 50.8% bias?",
      a3: "Stanford mathematicians Persi Diaconis and Susan Holmes found that physical coins precess slightly in the air, creating a 50.8% probability of landing on the same face that was facing up before the flip. Our digital CSPRNG eliminates this physical bias completely.",
      q4: "Can I play offline without an internet connection?",
      a4: "Yes! If your connection drops, the game automatically switches to offline mode using browser-level cryptographic random values and keeps your session active.",
      q5: "How does the global multi-language system work?",
      a5: "You can change languages anytime using the Language dropdown in the navbar. The application instantly updates all UI text, games, stats, and articles in real time.",
    },
    coinHistory: {
      title: "The 2,000-Year History of the Coin Toss",
      subtitle: "From ancient Roman emperors to NFL championships and historical decisions that shaped civilization.",
      backToGame: "Back to Coin Flip",
      era1Badge: "Ancient Rome (~44 BC)",
      era1Title: "Navia aut Caput (Ship or Head)",
      era1P: "In Ancient Rome, the game was known as 'Navia aut Caput' (Ship or Head). Coins featured the Emperor's profile on one side and a naval vessel prow on the other. Roman magistrates often tossed a coin of Julius Caesar to settle deadlocked legal disputes as an appeal to divine justice.",
      era2Badge: "Medieval Europe (~1300s)",
      era2Title: "Cross and Pile (Croce e Pila)",
      era2P: "In England and across medieval Europe, the game was called 'Cross and Pile'. The obverse showed a Christian cross, while the reverse was the 'pile' — the punch mark created during minting. The famous phrase 'neither cross nor pile' meant possessing no money whatsoever.",
      era3Badge: "Aviation History (1903)",
      era3Title: "The Wright Brothers' Coin Toss for Flight",
      era3P: "On December 14, 1903, at Kitty Hawk, North Carolina, aviation pioneers Wilbur and Orville Wright tossed a coin to decide who would pilot the world's very first powered flight attempt. Wilbur won the toss, though his initial attempt stalled before Orville's historic 12-second flight on December 17.",
      era4Badge: "American History (1845)",
      era4Title: "How Portland, Oregon Got Its Name",
      era4P: "In 1845, pioneers Asa Lovejoy (from Boston, Massachusetts) and Francis Pettygrove (from Portland, Maine) both wanted to name their newly surveyed Oregon settlement after their respective hometowns. They flipped a copper 1835 half-cent coin three times — Pettygrove won 2 out of 3, naming Portland, Oregon.",
      era5Badge: "Modern Era (1970s - Present)",
      era5Title: "The Super Bowl & International Sports",
      era5P: "Today, coin flips remain the universal impartial arbiter in modern sports — from cricket match tosses deciding batting order to the prestigious ceremonial coin toss at the NFL Super Bowl, watched by over 120 million fans worldwide.",
    },
    features: {
      backToGame: "Back to Coin Flip",
      title: "Everything the Game Can Do",
      subtitle: "A modern, secure coin flip experience — built with a realistic 3D flip, cloud-synced stats, and a fair, tamper-proof outcome every time.",
      ctaPlay: "Play Now",
      ctaSignup: "Create Free Account",
      f1Icon: "🪙",
      f1Title: "Realistic 3D Coin Flip",
      f1Text: "Watch a true 3D coin spin, tumble, and land with smooth physics-based animation — choose from US Quarter, UK 10p, Indian Rupee, UAE Dirham, and Penny designs.",
      f2Icon: "🎯",
      f2Title: "Heads or Tails Prediction",
      f2Text: "Call it in the air before every flip. Each outcome is judged against a cryptographically secure, truly independent 50/50 random draw.",
      f3Icon: "📜",
      f3Title: "Flip History",
      f3Text: "Your last 20 flips are recorded automatically — see exactly what you called, what landed, and when, any time you come back.",
      f4Icon: "📊",
      f4Title: "Live Score Tracking",
      f4Text: "A real-time scoreboard tracks total flips, wins, losses, win rate, and your best winning streak, updated the instant a coin lands.",
      f5Icon: "🔐",
      f5Title: "Secure Authentication",
      f5Text: "Sign up and log in with JWT-based sessions and bcrypt-hashed passwords. Your account and stats follow you across devices.",
      f6Icon: "🔊",
      f6Title: "Immersive Sound Effects",
      f6Text: "Satisfying flip and landing sound effects bring every toss to life, with a one-tap mute toggle whenever you want it quiet.",
      f7Icon: "📱",
      f7Title: "Fully Responsive UI",
      f7Text: "A polished layout with an adaptive mobile menu means the game feels just as good on a phone as it does on a desktop.",
      f8Icon: "☁️",
      f8Title: "Secure Cloud Storage",
      f8Text: "Every account, flip, and stat is stored in MongoDB Atlas, protected with TLS/SSL encryption in transit and AES-256 at rest.",
    },
    legal: {
      termsTitle: "Terms & Conditions",
      termsSubtitle: "Please review the terms and conditions governing the use of Heads or Tails.",
      privacyTitle: "Privacy Policy",
      privacySubtitle: "How we collect, protect, and handle your data with MongoDB Atlas encryption.",
      backToGame: "Back to Coin Flip",
      lastUpdated: "Last updated: August 2026",
      termsSec1Title: "1. Acceptance of Terms",
      termsSec1Text: "By accessing or using the Heads or Tails application, you agree to be bound by these Terms. This website is provided solely for entertainment, probability study, and recreational decision-making.",
      termsSec2Title: "2. No Real Money / No Gambling",
      termsSec2Text: "This application is purely a simulation and does not facilitate, support, or promote real-money gambling, sports betting, or financial wagers of any kind. No monetary prizes or rewards can be earned.",
      termsSec3Title: "3. Cryptographic Fairness",
      termsSec3Text: "All outcomes are generated using cryptographically secure random number generators (CSPRNG). We guarantee zero tampering or algorithmic skewing of results.",
      termsSec4Title: "4. User Accounts & Security",
      termsSec4Text: "You are responsible for maintaining the confidentiality of your account credentials. All passwords are encrypted with industry-standard bcrypt hashing before database storage.",
      privacySec1Title: "1. Information We Collect",
      privacySec1Text: "When you register an account, we collect your name, email address, and encrypted password. We also record your gameplay statistics (flip counts, wins, losses, streaks) to personalize your scoreboard.",
      privacySec2Title: "2. MongoDB Atlas Cloud Security",
      privacySec2Text: "Your account information is stored in MongoDB Atlas cloud clusters protected by TLS/SSL encryption in transit and AES-256 encryption at rest.",
      privacySec3Title: "3. Cookies & Local Storage",
      privacySec3Text: "We use browser local storage solely to remember your authentication session token and selected language preference. We do not use tracking cookies for ad profiling.",
      privacySec4Title: "4. Data Sharing & Deletion",
      privacySec4Text: "We never sell, rent, or trade your personal data to third parties. You may request account and score data deletion at any time by contacting support.",
    },
    auth: {
      loginTitle: "Welcome Back",
      loginSubtitle: "Sign in to track your coin flip stats and streaks across devices.",
      signupTitle: "Create Account",
      signupSubtitle: "Join to save your streaks, customize coins, and climb the leaderboard.",
      nameLabel: "Full Name",
      namePlaceholder: "e.g. Alex Morgan",
      emailLabel: "Email Address",
      emailPlaceholder: "name@example.com",
      passwordLabel: "Password",
      passwordPlaceholder: "At least 6 characters",
      loginSubmit: "Log In",
      signupSubmit: "Create Account",
      noAccount: "Don't have an account?",
      hasAccount: "Already have an account?",
      switchSignup: "Sign up now",
      switchLogin: "Log in",
      loggingIn: "Logging in...",
      signingUp: "Creating account...",
    },
    footer: {
      aboutTitle: "Heads or Tails Online",
      aboutText: "A realistic 3D online coin flip simulator engineered with cryptographically secure random number generation, realistic physics, sound effects, and multi-currency coin designs.",
      quickLinks: "Quick Navigation",
      playGame: "Coin Flip Game",
      blog: "Blog & Probability",
      faq: "FAQ & Help",
      history: "Coin Toss History",
      legal: "Legal & Policies",
      terms: "Terms & Conditions",
      privacy: "Privacy Policy",
      features: "Features",
      fairRng: "100% Fair CSPRNG",
      soundEffects: "3D Sound FX",
      globalCoins: "Multi-Currency Coins",
      statsTracker: "Real-time Stats",
      statusOnline: "API & Atlas Online",
      socialTitle: "Social & Community",
      disclaimer: "For entertainment and decision-making only — no real money or gambling involved. Outcomes are generated with fair 50/50 server-side cryptography.",
      copyright: "Heads or Tails. All rights reserved.",
      backToTop: "Back to top",
    },
  },
  es: {
    nav: {
      game: "Jugar",
      blog: "Blog",
      faq: "Preguntas",
      history: "Historia",
      language: "Idioma",
      login: "Iniciar sesión",
      signup: "Registrarse",
      logout: "Cerrar sesión",
      welcome: "Bienvenido",
    },
    game: {
      srTitle: "Cara o Cruz — Juego de Lanzamiento de Moneda en Línea",
      heads: "Cara",
      tails: "Cruz",
      flipBtn: "Lanzar la moneda",
      flippingBtn: "Lanzando…",
      statusFlipping: "Lanzando…",
      statusPrompt: "Elige un lado y lanza.",
      statusWonSuffix: "— ¡acertaste la tirada! 🎉",
      statusLostSuffix: "— más suerte en la próxima.",
      flippingCaption: "Lanzando la moneda {name}",
      soundMuted: "Silenciado",
      soundOn: "Sonido activado",
      soundMuteAria: "Silenciar efectos de sonido",
      soundUnmuteAria: "Activar efectos de sonido",
      offlineNote: "Jugando sin conexión — puntuación guardada solo en este dispositivo.",
      howItWorksTitle: "Cómo funciona el juego",
      howItWorksText:
        "Elige cara o cruz, selecciona un diseño de moneda y lanza. Cada resultado proviene de un sorteo aleatorio 50/50 justo e independiente, generado de forma criptográfica.",
    },
    scoreboard: {
      flips: "Tiradas",
      wins: "Victorias",
      losses: "Derrotas",
      winRate: "% Victorias",
      bestStreak: "Mejor racha",
    },
    history: {
      title: "Tiradas recientes",
      empty: "Tus tiradas aparecerán aquí — elige en el aire y juega.",
      guestPrompt: "Inicia sesión para guardar tus rachas y ver tu historial de tiradas recientes.",
      winBadge: "VICTORIA",
      lossBadge: "DERROTA",
      called: "Elegiste",
      landed: "Cayó",
    },
    coins: {
      quarter: "Cuarto de Dólar EE.UU.",
      uk10p: "10 Peniques Reino Unido",
      rupee: "Rupia India",
      dirham: "Dírham EAU",
      penny: "Centavo EE.UU.",
    },
    blog: {
      backToGame: "Volver al Juego",
      title: "Artículos y Probabilidad de Cara o Cruz",
      subtitle: "Teoría de probabilidades, toma de decisiones y la fascinante historia del lanzamiento de monedas.",
      readTime: "min de lectura",
      takeaway: "Conclusión Clave",
      article1Tag: "Matemáticas y Probabilidad",
      article1Title: "¿Es un lanzamiento de moneda 50/50 real? La ciencia detrás del giro",
      article1P1: "Durante siglos, la humanidad ha resuelto disputas y tomado decisiones con el simple lanzamiento de una moneda. Pero matemáticamente, ¿es exactamente 50.000% justo?",
      article1P2: "En un estudio de la Universidad de Stanford, se demostró que las monedas físicas tienen un ligero sesgo del 50.8% hacia el lado inicial debido al bamboleo en el aire.",
      article1P3: "En nuestro motor digital eliminamos este sesgo. Cada tirada se calcula con números aleatorios criptográficos seguros (CSPRNG) con un 50/50 perfecto.",
      article1Takeaway: "Las monedas físicas tienen micro-sesgos mecánicos, pero nuestro motor digital garantiza un 50.000% matemáticamente puro.",
      article2Tag: "Psicología y Decisiones",
      article2Title: "¿Fatiga de decisión? Por qué los líderes lanzan monedas",
      article2P1: "Los adultos toman unas 35.000 decisiones diarias. Esto genera fatiga de decisión y parálisis por análisis.",
      article2P2: "El polímata Piet Hein señaló que el poder de lanzar una moneda radica en que, en el instante en que está en el aire, tu subconsciente descubre qué resultado deseas realmente.",
      article2P3: "Cuando dudes entre dos opciones, lanza una moneda y observa lo que sientes antes de que caiga.",
      article2Takeaway: "Lanzar una moneda revela tus verdaderas preferencias subconscientes mientras gira en el aire.",
      article3Tag: "Historia y Cultura",
      article3Title: "De Julio César al Super Bowl: Historia milenaria de Cara o Cruz",
      article3P1: "En la Antigua Roma, el juego se llamaba 'Navia aut Caput' (Barco o Cabeza), con la cabeza del Emperador en una cara y la proa de un barco en la otra.",
      article3P2: "Los romanos consideraban la tirada un llamamiento a la justicia divina guiada por el espíritu de César.",
      article3P3: "Hoy, la tradición se mantiene en los mayores eventos deportivos mundiales, como el sorteo inicial del Super Bowl.",
      article3Takeaway: "Durante más de 2.000 años, el lanzamiento de moneda ha sido el árbitro imparcial del destino.",
    },
    faq: {
      title: "Preguntas Frecuentes (FAQ)",
      subtitle: "Todo lo que necesitas saber sobre probabilidades, imparcialidad criptográfica y cuentas.",
      backToGame: "Volver al Juego",
      q1: "¿Es este lanzamiento de moneda 100% justo (50/50)?",
      a1: "¡Sí! Nuestro motor de servidor utiliza números pseudoaleatorios criptográficamente seguros (CSPRNG en Node.js), garantizando un 50.000% exacto e imparcial.",
      q2: "¿Cómo guarda MongoDB Atlas mis estadísticas?",
      a2: "Al iniciar sesión, tu historial, victorias y rachas se guardan en la nube de MongoDB Atlas. Tu contraseña está cifrada con bcryptjs.",
      q3: "¿Por qué las monedas físicas tienen un 50.8% de sesgo?",
      a3: "Matemáticos de Stanford demostraron que el bamboleo físico genera un 50.8% de probabilidad hacia la cara inicial. Nuestro algoritmo digital no tiene sesgo físico.",
      q4: "¿Puedo jugar sin conexión a internet?",
      a4: "¡Sí! Si se interrumpe la conexión, el juego cambia automáticamente a modo offline en tu navegador.",
      q5: "¿Cómo funciona el cambio de idioma?",
      a5: "Puedes cambiar entre 7 idiomas desde el menú de navegación y toda la web se actualizará al instante.",
    },
    coinHistory: {
      title: "Historia Milenaria del Lanzamiento de Moneda",
      subtitle: "De los emperadores romanos al Super Bowl y decisiones históricas mundiales.",
      backToGame: "Volver al Juego",
      era1Badge: "Antigua Roma (~44 a.C.)",
      era1Title: "Navia aut Caput (Barco o Cabeza)",
      era1P: "En Roma se llamaba 'Navia aut Caput'. La moneda llevaba la efigie del César y la proa de una nave. Se usaba en juicios para dirimir disputas bajo la justicia divina.",
      era2Badge: "Edad Media (~1300)",
      era2Title: "Cruz y Pila (Croce e Pila)",
      era2P: "En Europa medieval, la moneda tenía una cruz cristiana en el anverso y la marca de acuñación ('pila') en el reverso.",
      era3Badge: "Aviación Histórica (1903)",
      era3Title: "La moneda de los hermanos Wright",
      era3P: "Wilbur y Orville Wright lanzaron una moneda para decidir quién pilotaría el primer vuelo a motor de la historia en Kitty Hawk. ¡Wilbur ganó la tirada!",
      era4Badge: "Historia de EE.UU. (1845)",
      era4Title: "Cómo Portland obtuvo su nombre",
      era4P: "Asa Lovejoy y Francis Pettygrove lanzaron un centavo tres veces para bautizar la ciudad con el nombre de su pueblo natal. Pettygrove ganó 2 de 3 y nació Portland, Oregón.",
      era5Badge: "Era Moderna (Actualidad)",
      era5Title: "El Super Bowl y el Deporte Mundial",
      era5P: "Hoy en día, el lanzamiento de moneda sigue siendo el árbitro supremo en el críquet internacional y en el inicio del Super Bowl ante 120 millones de espectadores.",
    },
    legal: {
      termsTitle: "Términos y Condiciones",
      termsSubtitle: "Condiciones de uso de Heads or Tails.",
      privacyTitle: "Política de Privacidad",
      privacySubtitle: "Cómo protegemos tus datos mediante cifrado y MongoDB Atlas.",
      backToGame: "Volver al Juego",
      lastUpdated: "Última actualización: Agosto 2026",
      termsSec1Title: "1. Aceptación de los Términos",
      termsSec1Text: "Al utilizar esta aplicación aceptas estos términos. El servicio se ofrece con fines recreativos y de toma de decisiones.",
      termsSec2Title: "2. Sin Dinero Real / Sin Apuestas",
      termsSec2Text: "Esta aplicación es una simulación gratuita y no permite apuestas de dinero real ni premios monetarios.",
      termsSec3Title: "3. Imparcialidad Criptográfica",
      termsSec3Text: "Todos los resultados se generan con algoritmos de aleatoriedad criptográfica CSPRNG sin manipulación.",
      termsSec4Title: "4. Seguridad de Cuentas",
      termsSec4Text: "Las contraseñas de los usuarios se cifran con bcrypt antes de almacenarse en la base de datos.",
      privacySec1Title: "1. Información que Recopilamos",
      privacySec1Text: "Recopilamos tu nombre, correo electrónico y estadísticas de juego para sincronizar tu marcador.",
      privacySec2Title: "2. Seguridad en MongoDB Atlas",
      privacySec2Text: "Los datos se almacenan en clústeres seguros de MongoDB Atlas con cifrado TLS/SSL y AES-256.",
      privacySec3Title: "3. Almacenamiento Local",
      privacySec3Text: "Utilizamos localStorage en tu navegador únicamente para recordar tu sesión y tu idioma.",
      privacySec4Title: "4. Sin Venta de Datos",
      privacySec4Text: "Nunca vendemos ni compartimos tu información personal con intermediarios de publicidad.",
    },
    auth: {
      loginTitle: "Bienvenido de nuevo",
      loginSubtitle: "Inicia sesión para sincronizar tus estadísticas y rachas.",
      signupTitle: "Crear Cuenta",
      signupSubtitle: "Únete para guardar tus rachas y personalizar monedas.",
      nameLabel: "Nombre Completo",
      namePlaceholder: "ej. Alex Morgan",
      emailLabel: "Correo Electrónico",
      emailPlaceholder: "correo@ejemplo.com",
      passwordLabel: "Contraseña",
      passwordPlaceholder: "Mínimo 6 caracteres",
      loginSubmit: "Iniciar sesión",
      signupSubmit: "Crear Cuenta",
      noAccount: "¿No tienes una cuenta?",
      hasAccount: "¿Ya tienes cuenta?",
      switchSignup: "Regístrate aquí",
      switchLogin: "Inicia sesión",
      loggingIn: "Iniciando sesión...",
      signingUp: "Creando cuenta...",
    },
    footer: {
      aboutTitle: "Cara o Cruz en Línea",
      aboutText: "Simulador de lanzamiento de moneda 3D realista con generación de números aleatorios criptográfica, efectos de sonido y monedas internacionales.",
      quickLinks: "Navegación Rápida",
      playGame: "Juego Cara o Cruz",
      blog: "Blog y Artículos",
      faq: "Preguntas Frecuentes",
      history: "Historia de la Moneda",
      legal: "Legal y Privacidad",
      terms: "Términos y Condiciones",
      privacy: "Política de Privacidad",
      features: "Características",
      fairRng: "RNG 100% Justo",
      soundEffects: "Sonido 3D Realista",
      globalCoins: "Monedas del Mundo",
      statsTracker: "Estadísticas en Vivo",
      statusOnline: "API y Atlas Activos",
      socialTitle: "Comunidad y Redes",
      disclaimer: "Para entretenimiento y toma de decisiones — sin dinero real ni apuestas involucradas.",
      copyright: "Cara o Cruz. Todos los derechos reservados.",
      backToTop: "Subir arriba",
    },
  },
  fr: {
    nav: {
      game: "Jouer",
      blog: "Blog",
      faq: "FAQ",
      history: "Histoire",
      language: "Langue",
      login: "Connexion",
      signup: "S'inscrire",
      logout: "Déconnexion",
      welcome: "Bienvenue",
    },
    game: {
      srTitle: "Pile ou Face — Jeu en ligne de lancer de pièce 3D",
      heads: "Pile",
      tails: "Face",
      flipBtn: "Lancer la pièce",
      flippingBtn: "Lancer en cours…",
      statusFlipping: "Lancer en cours…",
      statusPrompt: "Choisissez un côté et lancez.",
      statusWonSuffix: "— vous avez vu juste ! 🎉",
      statusLostSuffix: "— meilleure chance au prochain tour.",
      flippingCaption: "Lancer de la pièce : {name}",
      soundMuted: "Muet",
      soundOn: "Son activé",
      soundMuteAria: "Couper les effets sonores",
      soundUnmuteAria: "Activer les effets sonores",
      offlineNote: "Mode hors ligne — scores enregistrés sur cet appareil uniquement.",
      howItWorksTitle: "Comment fonctionne le jeu",
      howItWorksText:
        "Choisissez pile ou face, sélectionnez une pièce et lancez. Chaque tirage est 100% équitable et calculé de manière cryptographique.",
    },
    scoreboard: {
      flips: "Lancers",
      wins: "Victoires",
      losses: "Défaites",
      winRate: "% Victoires",
      bestStreak: "Meilleure série",
    },
    history: {
      title: "Lancers récents",
      empty: "Vos lancers apparaîtront ici — faites votre choix et lancez !",
      guestPrompt: "Connectez-vous pour enregistrer vos séries et consulter l'historique de vos lancers récents.",
      winBadge: "GAGNÉ",
      lossBadge: "PERDU",
      called: "Choisi",
      landed: "Résultat",
    },
    coins: {
      quarter: "Quarter Américain",
      uk10p: "10 Pence Britannique",
      rupee: "Roupie Indienne",
      dirham: "Dirham EAU",
      penny: "Penny Américain",
    },
    blog: {
      backToGame: "Retour au Jeu",
      title: "Articles et Probabilités Pile ou Face",
      subtitle: "Théorie des probabilités, prise de décision et histoire de pile ou face.",
      readTime: "min de lecture",
      takeaway: "Point Clé",
      article1Tag: "Mathématiques et Probabilités",
      article1Title: "Un lancer de pièce est-il vraiment 50/50 ? La science du spin",
      article1P1: "Depuis des siècles, l'humanité utilise la pièce pour décider. Mais est-ce mathématiquement 50.000% équitable ?",
      article1P2: "Une étude de Stanford a montré un biais physique de 50.8% selon la face de départ.",
      article1P3: "Notre moteur numérique élimine tout biais grâce à un algorithme cryptographique sécurisé CSPRNG.",
      article1Takeaway: "Notre simulateur garantit un 50.000% pur et impartial.",
      article2Tag: "Psychologie et Décision",
      article2Title: "Fatigue décisionnelle ? Pourquoi les leaders lancent une pièce",
      article2P1: "Chaque adulte prend environ 35 000 décisions par jour, entraînant une fatigue mentale.",
      article2P2: "Piet Hein a démontré que le lancer révèle instantanément ce que votre subconscient espère.",
      article2P3: "La prochaine fois que vous hésitez, lancez une pièce et écoutez votre intuition en plein vol.",
      article2Takeaway: "La pièce révèle vos véritables désirs pendant qu'elle tournoie dans les airs.",
      article3Tag: "Histoire et Culture",
      article3Title: "De Jules César au Super Bowl : L'histoire de Pile ou Face",
      article3P1: "À Rome antique, on jouait à 'Navia aut Caput' (Navire ou Tête).",
      article3P2: "Les magistrats romains faisaient appel au jugement divin avec le profil de César.",
      article3P3: "Aujourd'hui, cette tradition ouvre les plus grands matchs comme le Super Bowl.",
      article3Takeaway: "Depuis 2 000 ans, la pièce est le symbole universel du hasard équitable.",
    },
    faq: {
      title: "Foire Aux Questions (FAQ)",
      subtitle: "Tout savoir sur les probabilités, la sécurité cryptographique et les comptes.",
      backToGame: "Retour au Jeu",
      q1: "Ce lancer de pièce est-il vraiment équitable (50/50) ?",
      a1: "Oui ! Notre moteur utilise des nombres pseudo-aléatoires sécurisés (CSPRNG sous Node.js), garantissant une probabilité parfaite de 50.000%.",
      q2: "Comment MongoDB Atlas protège-t-il mes données ?",
      a2: "Vos statistiques et séries sont stockées sur MongoDB Atlas cloud avec chiffrement TLS/SSL et mots de passe sécurisés par bcryptjs.",
      q3: "Pourquoi les pièces physiques ont-elles un biais de 50.8% ?",
      a3: "Une étude de Stanford a montré que le mouvement physique favorise la face de départ. Notre algorithme numérique élimine tout biais physique.",
      q4: "Puis-je jouer hors ligne ?",
      a4: "Oui ! En cas de perte de connexion, le jeu passe automatiquement en mode hors ligne sur votre navigateur.",
      q5: "Comment fonctionne le sélecteur de langue ?",
      a5: "Changez de langue dans la barre de navigation et tout le site s'actualisera instantanément en temps réel.",
    },
    coinHistory: {
      title: "2 000 Ans d'Histoire du Lancer de Pièce",
      subtitle: "Des empereurs romains au Super Bowl et aux décisions historiques.",
      backToGame: "Retour au Jeu",
      era1Badge: "Rome Antique (~44 av. J.-C.)",
      era1Title: "Navia aut Caput (Navire ou Tête)",
      era1P: "À Rome, les pièces portaient le profil de l'empereur et la proue d'un navire pour trancher les litiges judiciaires.",
      era2Badge: "Moyen Âge (~1300)",
      era2Title: "Croix et Pile (Cross and Pile)",
      era2P: "En Europe médiévale, une face montrait la croix et l'autre la pile de frappe de la monnaie.",
      era3Badge: "Aviation (1903)",
      era3Title: "Le tirage au sort des frères Wright",
      era3P: "Wilbur et Orville Wright ont tiré à pile ou face pour savoir qui piloterait le tout premier vol motorisé de l'histoire.",
      era4Badge: "Histoire des États-Unis (1845)",
      era4Title: "Comment Portland a été baptisée",
      era4P: "Deux pionniers ont lancé une pièce pour nommer la ville en hommage à leur village d'origine. Pettygrove a gagné 2 lancers sur 3.",
      era5Badge: "Époque Contemporaine",
      era5Title: "Le Super Bowl et le Sport Mondial",
      era5P: "Le tirage au sort reste aujourd'hui le rituel inaugural officiel du cricket mondial et du Super Bowl de la NFL.",
    },
    legal: {
      termsTitle: "Conditions Générales d'Utilisation",
      termsSubtitle: "Consultez les règles d'utilisation de Heads or Tails.",
      privacyTitle: "Politique de Confidentialité",
      privacySubtitle: "Comment vos données sont protégées avec MongoDB Atlas.",
      backToGame: "Retour au Jeu",
      lastUpdated: "Dernière mise à jour : Août 2026",
      termsSec1Title: "1. Acceptation des Conditions",
      termsSec1Text: "En utilisant cette application, vous acceptez les présentes conditions. Le service est destiné au divertissement.",
      termsSec2Title: "2. Aucun Jeu d'Argent Réel",
      termsSec2Text: "Cette application est une simulation gratuite et ne comporte aucun pari d'argent réel.",
      termsSec3Title: "3. Équité Cryptographique",
      termsSec3Text: "Tous les tirages sont calculés via un algorithme cryptographique CSPRNG impartial.",
      termsSec4Title: "4. Sécurité des Comptes",
      termsSec4Text: "Vos mots de passe sont hachés avec bcryptjs avant tout stockage en base de données.",
      privacySec1Title: "1. Données Collectées",
      privacySec1Text: "Nous collectons votre nom, e-mail et statistiques de lancer pour synchroniser votre tableau des scores.",
      privacySec2Title: "2. Sécurité MongoDB Atlas",
      privacySec2Text: "Vos données sont hébergées sur des clusters cloud sécurisés avec chiffrement TLS/SSL et AES-256.",
      privacySec3Title: "3. Stockage Local",
      privacySec3Text: "Nous utilisons le localStorage uniquement pour conserver votre session et votre langue choisie.",
      privacySec4Title: "4. Aucune Vente de Données",
      privacySec4Text: "Nous ne vendons ni ne cédons aucune donnée personnelle à des tiers.",
    },
    auth: {
      loginTitle: "Bon retour",
      loginSubtitle: "Connectez-vous pour synchroniser vos statistiques et séries.",
      signupTitle: "Créer un Compte",
      signupSubtitle: "Rejoignez-nous pour sauvegarder vos séries de victoires.",
      nameLabel: "Nom complet",
      namePlaceholder: "ex. Alex Morgan",
      emailLabel: "Adresse e-mail",
      emailPlaceholder: "nom@exemple.com",
      passwordLabel: "Mot de passe",
      passwordPlaceholder: "Au moins 6 caractères",
      loginSubmit: "Se connecter",
      signupSubmit: "Créer un Compte",
      noAccount: "Vous n'avez pas de compte ?",
      hasAccount: "Avez-vous déjà un compte ?",
      switchSignup: "Inscrivez-vous",
      switchLogin: "Connectez-vous",
      loggingIn: "Connexion...",
      signingUp: "Création du compte...",
    },
    footer: {
      aboutTitle: "Pile ou Face en Ligne",
      aboutText: "Simulateur 3D avec tirage cryptographique équitable, effets sonores et pièces internationales.",
      quickLinks: "Navigation Rapide",
      playGame: "Jeu Pile ou Face",
      blog: "Blog & Analyses",
      faq: "Foire Aux Questions",
      history: "Histoire du Lancer",
      legal: "Mentions Légales",
      terms: "Conditions Générales",
      privacy: "Politique de Confidentialité",
      features: "Fonctionnalités",
      fairRng: "RNG 100% Équitable",
      soundEffects: "Sons 3D Réalistes",
      globalCoins: "Pièces Mondiales",
      statsTracker: "Statistiques en Direct",
      statusOnline: "API & Atlas Opérationnels",
      socialTitle: "Réseaux & Communauté",
      disclaimer: "À des fins de divertissement uniquement — aucun argent réel n'est engagé.",
      copyright: "Pile ou Face. Tous droits réservés.",
      backToTop: "Haut de page",
    },
  },
  de: {
    nav: {
      game: "Spiel starten",
      blog: "Blog",
      faq: "FAQ",
      history: "Historie",
      language: "Sprache",
      login: "Anmelden",
      signup: "Registrieren",
      logout: "Abmelden",
      welcome: "Willkommen",
    },
    game: {
      srTitle: "Kopf oder Zahl — Online 3D Münzwurf-Spiel",
      heads: "Kopf",
      tails: "Zahl",
      flipBtn: "Münze werfen",
      flippingBtn: "Fliegt…",
      statusFlipping: "Fliegt…",
      statusPrompt: "Wähle eine Seite und wirf.",
      statusWonSuffix: "— richtig getippt! 🎉",
      statusLostSuffix: "— beim nächsten Mal mehr Glück.",
      flippingCaption: "Aktuelle Münze: {name}",
      soundMuted: "Stumm",
      soundOn: "Ton an",
      soundMuteAria: "Ton stummschalten",
      soundUnmuteAria: "Ton einschalten",
      offlineNote: "Offline-Modus — Ergebnisse werden nur lokal gespeichert.",
      howItWorksTitle: "So funktioniert das Spiel",
      howItWorksText:
        "Wähle Kopf oder Zahl, suche eine Münze aus und wirf. Jedes Ergebnis basiert auf einem 100% fairen kryptografischen 50/50 Zufallsgenerator.",
    },
    scoreboard: {
      flips: "Würfe",
      wins: "Siege",
      losses: "Niederlagen",
      winRate: "Siegquote",
      bestStreak: "Beste Serie",
    },
    history: {
      title: "Letzte Würfe",
      empty: "Hier erscheinen deine Würfe — triff deine Wahl und wirf!",
      guestPrompt: "Melde dich an, um deine Siegesserien und den Wurf-Verlauf zu speichern.",
      winBadge: "SIEG",
      lossBadge: "NIEDERLAGE",
      called: "Gewählt",
      landed: "Gelandet",
    },
    coins: {
      quarter: "US Quarter",
      uk10p: "UK 10 Pence",
      rupee: "Indische Rupie",
      dirham: "VAE Dirham",
      penny: "US Penny",
    },
    blog: {
      backToGame: "Zurück zum Spiel",
      title: "Münzwurf Artikel & Analysen",
      subtitle: "Wahrscheinlichkeitstheorie, Entscheidungsfindung und Historie des Münzwurfs.",
      readTime: "Min. Lesezeit",
      takeaway: "Kernaussage",
      article1Tag: "Mathematik & Statistik",
      article1Title: "Ist ein Münzwurf wirklich 50/50? Die Physik des Wurfs",
      article1P1: "Seit Jahrhunderten treffen Menschen Entscheidungen per Münzwurf. Aber ist er mathematisch 50.000% fair?",
      article1P2: "Stanford-Wissenschaftler fanden heraus, dass physikalische Münzen zu 50,8% auf derselben Seite landen.",
      article1P3: "Unser digitaler Zufallsgenerator eliminiert diese Verzerrung durch kryptografische CSPRNG-Berechnungen.",
      article1Takeaway: "Unser Spiel bietet mathematisch reine 50,000% Wahrscheinlichkeit.",
      article2Tag: "Psychologie",
      article2Title: "Entscheidungsmüdigkeit? Warum kluge Köpfe Münzen werfen",
      article2P1: "Erwachsene treffen täglich 35.000 Entscheidungen, was zu Erschöpfung führt.",
      article2P2: "Piet Hein zeigte: Wenn die Münze in der Luft ist, weiß dein Unterbewusstsein sofort, was du willst.",
      article2P3: "Wirf die Münze und achte auf dein Bauchgefühl, bevor sie landet.",
      article2Takeaway: "Der Münzwurf offenbart deine verborgenen Wünsche.",
      article3Tag: "Geschichte & Kultur",
      article3Title: "Von Julius Cäsar zum Super Bowl: Die Geschichte von Kopf oder Zahl",
      article3P1: "Im alten Rom hieß das Spiel 'Navia aut Caput' (Schiff oder Kopf).",
      article3P2: "Römische Richter nutzten Münzen mit Cäsars Porträt für gerechte Entscheidungen.",
      article3P3: "Bis heute eröffnet der Münzwurf Sportereignisse wie den Super Bowl.",
      article3Takeaway: "Seit über 2.000 Jahren steht der Münzwurf für absolute Neutralität.",
    },
    faq: {
      title: "Häufig gestellte Fragen (FAQ)",
      subtitle: "Alles über Zufallsfairness, Wahrscheinlichkeiten und Benutzerkonten.",
      backToGame: "Zurück zum Spiel",
      q1: "Ist dieser Münzwurf 100% fair (50/50)?",
      a1: "Ja! Unsere Engine nutzt kryptografisch sichere Pseudozufallszahlen (CSPRNG in Node.js) für garantierte 50,000% Chancengleichheit.",
      q2: "Wie sichert MongoDB Atlas meine Daten?",
      a2: "Deine Spielstände und Serien werden sicher in der MongoDB Atlas Cloud mit TLS/SSL und bcryptjs-Passwortverschlüsselung gespeichert.",
      q3: "Warum haben echte Münzen 50,8% Verzerrung?",
      a3: "Stanford-Forscher bewiesen eine leichte Präzessionsbewegung physikalischer Münzen. Unser digitaler Wurf ist frei von jeder mechanischen Verzerrung.",
      q4: "Kann ich offline spielen?",
      a4: "Ja! Bei Verbindungsverlust schaltet das Spiel automatisch in den lokalen Offline-Modus deines Browsers.",
      q5: "Wie funktioniert die Sprachauswahl?",
      a5: "Wähle einfach deine Sprache in der Navigationsleiste — die gesamte Website passt sich sofort an.",
    },
    coinHistory: {
      title: "2.000 Jahre Geschichte des Münzwurfs",
      subtitle: "Von römischen Kaisern bis zum Super Bowl und weltverändernden Beschlüssen.",
      backToGame: "Zurück zum Spiel",
      era1Badge: "Antikes Rom (~44 v. Chr.)",
      era1Title: "Navia aut Caput (Schiff oder Kopf)",
      era1P: "Im antiken Rom trug die Münze das Profil des Cäsars und den Schiffsbug zur göttlichen Streitschlichtung.",
      era2Badge: "Mittelalter (~1300)",
      era2Title: "Kreuz und Münze (Cross and Pile)",
      era2P: "Im mittelalterlichen Europa zeigte die Vorderseite das Kreuz und die Rückseite den Prägestempel.",
      era3Badge: "Luftfahrtgeschichte (1903)",
      era3Title: "Der Münzwurf der Gebrüder Wright",
      era3P: "Wilbur und Orville Wright warfen eine Münze, um zu entscheiden, wer den allerersten Motorflug der Menschheit durchführen durfte.",
      era4Badge: "US-Geschichte (1845)",
      era4Title: "Wie Portland zu seinem Namen kam",
      era4P: "Zwei Siedler warfen dreimal eine Kupfermünze, um die Stadt nach ihrer Heimatstadt zu benennen. Pettygrove gewann 2 von 3 Würfen.",
      era5Badge: "Moderne Epoche",
      era5Title: "Super Bowl und Weltsport",
      era5P: "Auch heute ist der Münzwurf der unverzichtbare Auftakt im internationalen Cricket und beim NFL Super Bowl.",
    },
    legal: {
      termsTitle: "Nutzungsbedingungen",
      termsSubtitle: "Regeln und Bestimmungen für Heads or Tails.",
      privacyTitle: "Datenschutzerklärung",
      privacySubtitle: "Informationen zu Datenschutz und MongoDB Atlas Sicherheit.",
      backToGame: "Zurück zum Spiel",
      lastUpdated: "Stand: August 2026",
      termsSec1Title: "1. Geltungsbereich",
      termsSec1Text: "Mit der Nutzung dieser Anwendung stimmen Sie den Nutzungsbedingungen zu. Das Spiel dient der Unterhaltung.",
      termsSec2Title: "2. Kein Echtgeld / Kein Glücksspiel",
      termsSec2Text: "Diese Website ist eine kostenlose Simulation ohne Wetteinsätze oder Gewinnausschüttungen.",
      termsSec3Title: "3. Kryptografische Fairness",
      termsSec3Text: "Alle Ergebnisse basieren auf manipulationsfreier kryptografischer CSPRNG-Zufallsberechnung.",
      termsSec4Title: "4. Kontosicherheit",
      termsSec4Text: "Passwörter werden vor der Speicherung in der Datenbank mit bcrypt gehasht.",
      privacySec1Title: "1. Erhobene Daten",
      privacySec1Text: "Wir speichern Name, E-Mail und Statistiken zur Synchronisation deiner Punktzahlen.",
      privacySec2Title: "2. MongoDB Atlas Sicherheit",
      privacySec2Text: "Die Speicherung erfolgt in geschützten Clustern mit TLS/SSL und AES-256 Verschlüsselung.",
      privacySec3Title: "3. Lokaler Speicher",
      privacySec3Text: "localStorage wird ausschließlich zur Sitzungsspeicherung und Sprachwahl verwendet.",
      privacySec4Title: "4. Keine Datenweitergabe",
      privacySec4Text: "Wir verkaufen oder vermitteln niemals Nutzerdaten an Dritte oder Werbenetzwerke.",
    },
    auth: {
      loginTitle: "Willkommen zurück",
      loginSubtitle: "Melde dich an, um deine Statistiken zu synchronisieren.",
      signupTitle: "Konto erstellen",
      signupSubtitle: "Erstelle ein Konto für deine Siegesserien.",
      nameLabel: "Vollständiger Name",
      namePlaceholder: "z.B. Alex Morgan",
      emailLabel: "E-Mail-Adresse",
      emailPlaceholder: "name@beispiel.de",
      passwordLabel: "Passwort",
      passwordPlaceholder: "Mindestens 6 Zeichen",
      loginSubmit: "Anmelden",
      signupSubmit: "Konto erstellen",
      noAccount: "Noch kein Konto?",
      hasAccount: "Bereits ein Konto?",
      switchSignup: "Jetzt registrieren",
      switchLogin: "Anmelden",
      loggingIn: "Wird angemeldet...",
      signingUp: "Konto wird erstellt...",
    },
    footer: {
      aboutTitle: "Kopf oder Zahl Online",
      aboutText: "Realistischer 3D-Münzwurf-Simulator mit kryptografischem Zufall, Soundeffekten und internationalen Münzen.",
      quickLinks: "Schnellnavigation",
      playGame: "Münzwurf-Spiel",
      blog: "Blog & Artikel",
      faq: "Häufige Fragen (FAQ)",
      history: "Münzwurf-Historie",
      legal: "Rechtliches & Datenschutz",
      terms: "Nutzungsbedingungen",
      privacy: "Datenschutzerklärung",
      features: "Funktionen",
      fairRng: "100% fairer Zufall",
      soundEffects: "3D Soundeffekte",
      globalCoins: "Internationale Münzen",
      statsTracker: "Echtzeit-Statistik",
      statusOnline: "API & Atlas online",
      socialTitle: "Soziale Netzwerke",
      disclaimer: "Nur zur Unterhaltung und Entscheidungsfindung — kein Echtgeld.",
      copyright: "Kopf oder Zahl. Alle Rechte vorbehalten.",
      backToTop: "Nach oben",
    },
  },
  it: {
    nav: {
      game: "Gioca",
      blog: "Blog",
      faq: "FAQ",
      history: "Storia",
      language: "Lingua",
      login: "Accedi",
      signup: "Registrati",
      logout: "Esci",
      welcome: "Bentornato",
    },
    game: {
      srTitle: "Testa o Croce — Lancio della Moneta 3D Online",
      heads: "Testa",
      tails: "Croce",
      flipBtn: "Lancia la moneta",
      flippingBtn: "Lancio in corso…",
      statusFlipping: "Lancio in corso…",
      statusPrompt: "Scegli un lato e lancia.",
      statusWonSuffix: "— hai indovinato! 🎉",
      statusLostSuffix: "— più fortuna al prossimo lancio.",
      flippingCaption: "Moneta attuale: {name}",
      soundMuted: "Muto",
      soundOn: "Audio attivo",
      soundMuteAria: "Disattiva audio",
      soundUnmuteAria: "Attiva audio",
      offlineNote: "Modalità offline — punteggi salvati solo su questo dispositivo.",
      howItWorksTitle: "Come funziona il gioco",
      howItWorksText:
        "Scegli testa o croce, seleziona una moneta e lancia. Ogni risultato è generato con un algoritmo crittografico sicuro 50/50.",
    },
    scoreboard: {
      flips: "Lanci",
      wins: "Vittorie",
      losses: "Sconfitte",
      winRate: "% Vittorie",
      bestStreak: "Miglior serie",
    },
    history: {
      title: "Lanci recenti",
      empty: "I tuoi lanci appariranno qui — fai la tua scelta e lancia!",
      guestPrompt: "Accedi per salvare le tue serie e visualizzare la cronologia dei tuoi lanci recenti.",
      winBadge: "VITTORIA",
      lossBadge: "SCONFITTA",
      called: "Scelto",
      landed: "Uscito",
    },
    coins: {
      quarter: "Quarter USA",
      uk10p: "10 Pence UK",
      rupee: "Rupia Indiana",
      dirham: "Dirham EAU",
      penny: "Penny USA",
    },
    blog: {
      backToGame: "Torna al Gioco",
      title: "Articoli e Probabilità Testa o Croce",
      subtitle: "Teoria della probabilità, processi decisionali e storia del lancio della moneta.",
      readTime: "min di lettura",
      takeaway: "Punto Chiave",
      article1Tag: "Matematica e Statistica",
      article1Title: "Il lancio della moneta è davvero 50/50? La fisica del lancio",
      article1P1: "Da millenni usiamo la moneta per decidere, ma è esattamente 50.000% imparziale?",
      article1P2: "Uno studio di Stanford ha evidenziato un lieve bias del 50,8% nelle monete fisiche.",
      article1P3: "Il nostro motore digitale elimina ogni imperfezione con crittografia CSPRNG.",
      article1Takeaway: "Garantiamo una probabilità pura al 50.000%.",
      article2Tag: "Psicologia",
      article2Title: "Troppe decisioni? Perché i leader lanciano la moneta",
      article2P1: "Prendere migliaia di decisioni al giorno causa affaticamento mentale.",
      article2P2: "Mentre la moneta è in aria, il tuo inconscio capisce all'istante cosa desideri.",
      article2P3: "Lancia la moneta e ascolta la tua reazione istintiva.",
      article2Takeaway: "La moneta svela le tue vere preferenze nel momento del volo.",
      article3Tag: "Storia e Cultura",
      article3Title: "Da Giulio Cesare al Super Bowl: Storia di Testa o Croce",
      article3P1: "Nell'Antica Roma si giocava a 'Navia aut Caput' (Nave o Testa).",
      article3P2: "I magistrati romani invocavano il giudizio della moneta di Cesare per risolvere contese.",
      article3P3: "La tradizione continua oggi nei più grandi stadi del mondo.",
      article3Takeaway: "Da oltre 2000 anni il simbolo universale del caso neutrale.",
    },
    faq: {
      title: "Domande Frequenti (FAQ)",
      subtitle: "Tutto su probabilità, imparzialità crittografica e account.",
      backToGame: "Torna al Gioco",
      q1: "Questo lancio della moneta è imparziale al 50/50?",
      a1: "Sì! Il nostro algoritmo CSPRNG garantisce una probabilità perfettamente bilanciata al 50.000%.",
      q2: "Come salva i dati MongoDB Atlas?",
      a2: "I tuoi record e serie sono salvati in sicurezza sul cloud MongoDB Atlas con password cifrate in bcryptjs.",
      q3: "Perché le monete fisiche hanno una deviazione del 50,8%?",
      a3: "La rotazione fisica produce una leggera asimmetria. Il nostro generatore digitale azzera ogni deviazione.",
      q4: "Posso giocare offline?",
      a4: "Sì! Se perdi la connessione il gioco attiva automaticamente la modalità offline locale.",
      q5: "Come cambio lingua?",
      a5: "Usa il selettore lingua nella barra superiore e la pagina si tradurrà all'istante.",
    },
    coinHistory: {
      title: "2000 Anni di Storia del Lancio della Moneta",
      subtitle: "Dagli imperatori romani al Super Bowl e alle grandi svolte storiche.",
      backToGame: "Torna al Gioco",
      era1Badge: "Antica Roma (~44 a.C.)",
      era1Title: "Navia aut Caput (Nave o Testa)",
      era1P: "I romani lanciavano la moneta di Cesare con l'effigie imperiale e la prora navale per dirimere le cause civili.",
      era2Badge: "Medioevo (~1300)",
      era2Title: "Croce e Pila (Cross and Pile)",
      era2P: "In Europa medievale una faccia mostrava la croce e l'altra la pila di coniazione.",
      era3Badge: "Aviazione (1903)",
      era3Title: "La moneta dei fratelli Wright",
      era3P: "Wilbur e Orville Wright decisero con un lancio chi avrebbe effettuato il primo volo a motore della storia.",
      era4Badge: "Storia USA (1845)",
      era4Title: "Il nome della città di Portland",
      era4P: "Due pionieri tirarono a sorte per dare il nome alla città; Pettygrove vinse 2 lanci su 3 e scelse Portland.",
      era5Badge: "Era Contemporanea",
      era5Title: "Super Bowl e Sport Internazionale",
      era5P: "Il sorteggio con la moneta apre ancora oggi i mondiali di cricket e il Super Bowl NFL.",
    },
    legal: {
      termsTitle: "Termini e Condizioni",
      termsSubtitle: "Condizioni generali di utilizzo del servizio.",
      privacyTitle: "Informativa sulla Privacy",
      privacySubtitle: "Protezione dei dati personali e sicurezza MongoDB Atlas.",
      backToGame: "Torna al Gioco",
      lastUpdated: "Ultimo aggiornamento: Agosto 2026",
      termsSec1Title: "1. Accettazione dei Termini",
      termsSec1Text: "L'uso dell'applicazione implica l'accettazione delle presenti condizioni per fini di intrattenimento.",
      termsSec2Title: "2. Nessun Gioco d'Azzardo Reale",
      termsSec2Text: "L'applicazione è una simulazione e non consente scommesse in denaro reale.",
      termsSec3Title: "3. Equità Crittografica",
      termsSec3Text: "Tutti i lanci sono generati con algoritmi crittografici CSPRNG imparziali.",
      termsSec4Title: "4. Sicurezza dell'Account",
      termsSec4Text: "Le password sono protette mediante hashing crittografico bcrypt prima del salvataggio.",
      privacySec1Title: "1. Dati Raccolti",
      privacySec1Text: "Raccogliamo nome, email e statistiche di gioco per sincronizzare il tuo profilo.",
      privacySec2Title: "2. Sicurezza MongoDB Atlas",
      privacySec2Text: "I dati sono archiviati su cluster cloud protetti da crittografia TLS/SSL e AES-256.",
      privacySec3Title: "3. Memoria Locale",
      privacySec3Text: "Il localStorage viene usato unicamente per memorizzare la sessione e la lingua preferita.",
      privacySec4Title: "4. Nessuna Cessione Dati",
      privacySec4Text: "Non vendiamo né cediamo dati personali a società pubblicitarie terze.",
    },
    auth: {
      loginTitle: "Bentornato",
      loginSubtitle: "Accedi per salvare statistiche e serie di vittorie.",
      signupTitle: "Crea un Account",
      signupSubtitle: "Registrati per conservare i tuoi record.",
      nameLabel: "Nome completo",
      namePlaceholder: "es. Alex Morgan",
      emailLabel: "Indirizzo Email",
      emailPlaceholder: "nome@esempio.it",
      passwordLabel: "Password",
      passwordPlaceholder: "Almeno 6 caratteri",
      loginSubmit: "Accedi",
      signupSubmit: "Crea Account",
      noAccount: "Non hai un account?",
      hasAccount: "Hai già un account?",
      switchSignup: "Registrati ora",
      switchLogin: "Accedi",
      loggingIn: "Accesso in corso...",
      signingUp: "Creazione account...",
    },
    footer: {
      aboutTitle: "Testa o Croce Online",
      aboutText: "Simulatore 3D con crittografia equa, effetti audio realistici e monete internazionali.",
      quickLinks: "Navigazione Rapida",
      playGame: "Gioco Testa o Croce",
      blog: "Blog & Probabilità",
      faq: "Domande Frequenti (FAQ)",
      history: "Storia della Moneta",
      legal: "Note Legali & Privacy",
      terms: "Termini e Condizioni",
      privacy: "Informativa Privacy",
      features: "Caratteristiche",
      fairRng: "RNG 100% Equo",
      soundEffects: "Audio 3D Realistico",
      globalCoins: "Monete dal Mondo",
      statsTracker: "Statistiche Live",
      statusOnline: "API & Atlas Attivi",
      socialTitle: "Social & Community",
      disclaimer: "Solo a scopo di intrattenimento — nessun denaro reale coinvolto.",
      copyright: "Testa o Croce. Tutti i diritti riservati.",
      backToTop: "Torna su",
    },
  },
  hi: {
    nav: {
      game: "सिक्का उछालें",
      blog: "ब्लॉग",
      faq: "एफएक्यू",
      history: "इतिहास",
      language: "भाषा",
      login: "लॉग इन",
      signup: "साइन अप",
      logout: "लॉग आउट",
      welcome: "स्वागत है",
    },
    game: {
      srTitle: "हेड या टेल — ऑनलाइन 3D सिक्का टॉस गेम",
      heads: "हेड्स",
      tails: "टेल्स",
      flipBtn: "सिक्का उछालें",
      flippingBtn: "उछल रहा है…",
      statusFlipping: "सिक्का हवा में है…",
      statusPrompt: "हेड या टेल चुनें और सिक्का उछालें।",
      statusWonSuffix: "— आपका अनुमान बिल्कुल सही था! 🎉",
      statusLostSuffix: "— अगली बार बेहतर किस्मत।",
      flippingCaption: "सिक्का: {name}",
      soundMuted: "म्यूट",
      soundOn: "ध्वनि चालू",
      soundMuteAria: "ध्वनि बंद करें",
      soundUnmuteAria: "ध्वनि चालू करें",
      offlineNote: "ऑफ़लाइन मोड — स्कोर केवल इसी डिवाइस पर सुरक्षित है।",
      howItWorksTitle: "गेम कैसे काम करता है",
      howItWorksText:
        "हेड्स या टेल्स चुनें, सिक्के का डिज़ाइन तय करें और फ्लिप करें। प्रत्येक परिणाम निष्पक्ष और क्रिप्टोग्राफ़िक 50/50 यादृच्छिक गणना पर आधारित है।",
    },
    scoreboard: {
      flips: "कुल टॉस",
      wins: "जीत",
      losses: "हार",
      winRate: "जीत दर",
      bestStreak: "सर्वश्रेष्ठ स्ट्रीक",
    },
    history: {
      title: "हाल के टॉस",
      empty: "आपके टॉस के परिणाम यहाँ दिखेंगे — सिक्का उछालें!",
      guestPrompt: "अपनी स्ट्रीक्स को सुरक्षित रखने और हाल के टॉस का इतिहास देखने के लिए लॉगिन करें।",
      winBadge: "जीत",
      lossBadge: "हार",
      called: "चुना",
      landed: "आया",
    },
    coins: {
      quarter: "अमेरिकी क्वार्टर",
      uk10p: "ब्रिटिश 10 पेंस",
      rupee: "भारतीय रुपया",
      dirham: "यूएई दिरहम",
      penny: "अमेरिकी पेनी",
    },
    blog: {
      backToGame: "खेल पर वापस जाएं",
      title: "सिक्का उछालने के रोचक लेख और विश्लेषण",
      subtitle: "संभाव्यता सिद्धांत, निर्णय क्षमता और हेड या टेल का 2,000 साल पुराना इतिहास।",
      readTime: "मिनट पढ़ने का समय",
      takeaway: "मुख्य सीख",
      article1Tag: "गणित और संभाव्यता",
      article1Title: "क्या सिक्का उछालना वास्तव में 50/50 होता है? जानिए विज्ञान",
      article1P1: "सदियों से लोग निर्णय लेने के लिए सिक्का उछालते आए हैं। लेकिन क्या यह वास्तव में 50.000% निष्पक्ष है?",
      article1P2: "स्टैनफोर्ड विश्वविद्यालय के अध्ययन के अनुसार भौतिक सिक्के में 50.8% का मामूली झुकाव हो सकता है।",
      article1P3: "हमारे डिजिटल गेम में क्रिप्टोग्राफिक CSPRNG का उपयोग किया जाता है जो पूरी तरह से 50.000% निष्पक्ष है।",
      article1Takeaway: "हमारा डिजिटल इंजन गणितीय रूप से शुद्ध 50/50 परिणाम सुनिश्चित करता है।",
      article2Tag: "मनोविज्ञान",
      article2Title: "निर्णय लेने में असमंजस? जानिए सिक्का उछालने का मनोवैज्ञानिक लाभ",
      article2P1: "इंसान दिन भर में हजारों निर्णय लेता है जिससे मानसिक थकान होती है।",
      article2P2: "जब सिक्का हवा में होता है, तो आपका अवचेतन मन तुरंत पहचान लेता है कि आप वास्तव में क्या चाहते हैं।",
      article2P3: "दुविधा में सिक्का उछालें और हवा में रहते हुए अपनी आंतरिक भावना पर ध्यान दें।",
      article2Takeaway: "सिक्का हवा में घूमते समय आपकी वास्तविक इच्छा प्रकट कर देता है।",
      article3Tag: "इतिहास और संस्कृति",
      article3Title: "जूलियस सीज़र से सुपर बाउल तक: हेड या टेल का इतिहास",
      article3P1: "प्राचीन रोम में इस खेल को 'नाविया ऑट कैपुट' (जहाज या सिर) कहा जाता था।",
      article3P2: "रोमन न्यायाधीश विवादों को सुलझाने के लिए सीज़र के सिक्के का उपयोग करते थे।",
      article3P3: "आज यह परंपरा क्रिकेट मैचों और सुपर बाउल जैसे बड़े खेलों में जीवित है।",
      article3Takeaway: "2,000 वर्षों से सिक्का निष्पक्षता का वैश्विक प्रतीक रहा है।",
    },
    faq: {
      title: "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
      subtitle: "सिक्का फ्लिप निष्पक्षता, क्रिप्टोग्राफिक एल्गोरिदम और गेम से जुड़े सभी उत्तर।",
      backToGame: "सिक्का टॉस पर लौटें",
      q1: "क्या यह सिक्का फ्लिप वास्तव में 50/50 निष्पक्ष है?",
      a1: "हाँ! हमारा सर्वर CSPRNG क्रिप्टोग्राफिक रैंडमनेस का उपयोग करता है जो 50.000% शुद्ध निष्पक्षता सुनिश्चित करता है।",
      q2: "MongoDB Atlas में मेरा डेटा कैसे सुरक्षित रहता है?",
      a2: "आपका स्कोर और स्ट्रीक डेटा सुरक्षित MongoDB Atlas क्लाउड में स्टोर होता है और पासवर्ड bcrypt द्वारा एन्क्रिप्टेड है।",
      q3: "क्या असली सिक्के में 50.8% का झुकाव होता है?",
      a3: "स्टैनफोर्ड के शोधकर्ताओं ने पाया कि असली सिक्के हवा में घूमते समय थोड़े असमान होते हैं, लेकिन हमारे डिजिटल टॉस में शून्य पूर्वाग्रह है।",
      q4: "क्या मैं ऑफ़लाइन खेल सकता हूँ?",
      a4: "हाँ! इंटरनेट बंद होने पर गेम अपने आप ऑफ़लाइन मोड में सुरक्षित रूप से चलता है।",
      q5: "भाषा कैसे बदलें?",
      a5: "नेवबार में भाषा ड्रॉपडाउन से अपनी पसंदीदा भाषा चुनें, पूरा ऐप तुरंत बदल जाएगा।",
    },
    coinHistory: {
      title: "सिक्का टॉस का 2,000 वर्षों का स्वर्णिम इतिहास",
      subtitle: "रोमन सम्राटों से लेकर राइट ब्रदर्स और सुपर बाउल तक की ऐतिहासिक यात्रा।",
      backToGame: "सिक्का टॉस पर लौटें",
      era1Badge: "प्राचीन रोम (~44 ई.पू.)",
      era1Title: "नाविया ऑट कैपुट (जहाज या सिर)",
      era1P: "प्राचीन रोम में सम्राट सीज़र के सिक्के से कानूनी विवादों को सुलझाया जाता था जिसे दैवीय न्याय माना जाता था।",
      era2Badge: "मध्यकालीन यूरोप (~1300)",
      era2Title: "क्रॉस और पाइल (Cross and Pile)",
      era2P: "मध्यकालीन सिक्कों के एक तरफ पवित्र क्रॉस और दूसरी तरफ टक्साल का निशान होता था।",
      era3Badge: "विमानन इतिहास (1903)",
      era3Title: "राइट ब्रदर्स का ऐतिहासिक सिक्का टॉस",
      era3P: "विल्बर और ओरविल राइट ने दुनिया की पहली हवाई उड़ान उड़ाने का फैसला एक सिक्का उछालकर किया था।",
      era4Badge: "अमेरिकी इतिहास (1845)",
      era4Title: "पोर्टलैंड शहर का नामकरण",
      era4P: "दो अमेरिकी अग्रदूतों ने शहर का नाम रखने के लिए तीन बार सिक्का उछाला और पोर्टलैंड नाम तय हुआ।",
      era5Badge: "आधुनिक युग (वर्तमान)",
      era5Title: "क्रिकेट और सुपर बाउल",
      era5P: "आज भी अंतरराष्ट्रीय क्रिकेट और एनएफएल सुपर बाउल का आरंभ सिक्के के निष्पक्ष टॉस से होता है।",
    },
    legal: {
      termsTitle: "नियम और शर्तें (Terms & Conditions)",
      termsSubtitle: "हेड्स या टेल्स ऐप के उपयोग के नियम।",
      privacyTitle: "गोपनीयता नीति (Privacy Policy)",
      privacySubtitle: "MongoDB Atlas और डेटा सुरक्षा की पूरी जानकारी।",
      backToGame: "सिक्का टॉस पर लौटें",
      lastUpdated: "अंतिम अपडेट: अगस्त 2026",
      termsSec1Title: "1. शर्तों की स्वीकृति",
      termsSec1Text: "इस ऐप का उपयोग करके आप इन नियमों से सहमत होते हैं। यह केवल मनोरंजन के लिए है।",
      termsSec2Title: "2. कोई वास्तविक धन या जुआ नहीं",
      termsSec2Text: "यह पूरी तरह से मुफ्त सिमुलेशन है। इसमें किसी भी प्रकार का जुआ या वित्तीय दांव शामिल नहीं है।",
      termsSec3Title: "3. क्रिप्टोग्राफ़िक निष्पक्षता",
      termsSec3Text: "सभी परिणाम निष्पक्ष CSPRNG रैंडम जनरेटर द्वारा तैयार किए जाते हैं।",
      termsSec4Title: "4. खाता सुरक्षा",
      termsSec4Text: "आपके पासवर्ड डेटाबेस में सुरक्षित bcrypt हैशिंग द्वारा सुरक्षित रखे जाते हैं।",
      privacySec1Title: "1. संगृहीत जानकारी",
      privacySec1Text: "हम आपका नाम, ईमेल और स्कोरबोर्ड डेटा सुरक्षित रूप से सिंक करते हैं।",
      privacySec2Title: "2. MongoDB Atlas क्लाउड सुरक्षा",
      privacySec2Text: "डेटा TLS/SSL और AES-256 एन्क्रिप्शन के साथ सुरक्षित क्लाउड में संग्रहीत है।",
      privacySec3Title: "3. लोकल स्टोरेज",
      privacySec3Text: "हम केवल सत्र और भाषा सेटिंग याद रखने के लिए localStorage का उपयोग करते हैं।",
      privacySec4Title: "4. कोई डेटा बिक्री नहीं",
      privacySec4Text: "हम कभी भी आपकी व्यक्तिगत जानकारी किसी तीसरे पक्ष को नहीं बेचते।",
    },
    auth: {
      loginTitle: "वापसी पर स्वागत है",
      loginSubtitle: "अपने आंकड़ों और स्ट्रीक्स को सहेजने के लिए लॉगिन करें।",
      signupTitle: "नया खाता बनाएं",
      signupSubtitle: "सिक्का फ्लिप लीडरबोर्ड में शामिल हों।",
      nameLabel: "पूरा नाम",
      namePlaceholder: "उदा. राहुल शर्मा",
      emailLabel: "ईमेल पता",
      emailPlaceholder: "name@example.com",
      passwordLabel: "पासवर्ड",
      passwordPlaceholder: "कम से कम 6 अक्षर",
      loginSubmit: "लॉग इन करें",
      signupSubmit: "खाता बनाएं",
      noAccount: "खाता नहीं है?",
      hasAccount: "पहले से खाता है?",
      switchSignup: "साइन अप करें",
      switchLogin: "लॉग इन करें",
      loggingIn: "लॉगिन हो रहा है...",
      signingUp: "खाता बन रहा है...",
    },
    footer: {
      aboutTitle: "हेड्स या टेल्स ऑनलाइन",
      aboutText: "क्रिप्टोग्राफिक निष्पक्षता, 3D एनीमेशन और अंतरराष्ट्रीय सिक्कों से लैस गेम।",
      quickLinks: "त्वरित नेविगेशन",
      playGame: "सिक्का टॉस गेम",
      blog: "ब्लॉग और लेख",
      faq: "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
      history: "सिक्के का इतिहास",
      legal: "कानूनी व नीतियां",
      terms: "नियम व शर्तें",
      privacy: "गोपनीयता नीति",
      features: "विशेषताएं",
      fairRng: "100% निष्पक्ष CSPRNG",
      soundEffects: "3D ध्वनि प्रभाव",
      globalCoins: "विश्व के सिक्के",
      statsTracker: "लाइव आँकड़े",
      statusOnline: "API और Atlas चालू हैं",
      socialTitle: "सोशल मीडिया व कम्युनिटी",
      disclaimer: "केवल मनोरंजन और निर्णय लेने के लिए — इसमें कोई वास्तविक धन शामिल नहीं है।",
      copyright: "हेड्स या टेल्स. सर्वाधिकार सुरक्षित।",
      backToTop: "शीर्ष पर जाएं",
    },
  },
  ja: {
    nav: {
      game: "ゲームをプレイ",
      blog: "ブログ",
      faq: "よくある質問",
      history: "歴史",
      language: "言語",
      login: "ログイン",
      signup: "新規登録",
      logout: "ログアウト",
      welcome: "おかえりなさい",
    },
    game: {
      srTitle: "表か裏か — 3Dオンライン コイントスゲーム",
      heads: "表 (Heads)",
      tails: "裏 (Tails)",
      flipBtn: "コインを投げる",
      flippingBtn: "回転中…",
      statusFlipping: "コインが回転しています…",
      statusPrompt: "表か裏を選んでコインを投げましょう。",
      statusWonSuffix: "— 見事に的中しました！ 🎉",
      statusLostSuffix: "— 次のチャンスに期待しましょう。",
      flippingCaption: "選択中: {name}",
      soundMuted: "ミュート中",
      soundOn: "サウンドON",
      soundMuteAria: "効果音をミュート",
      soundUnmuteAria: "効果音をオンにする",
      offlineNote: "オフラインモード — スコアはこの端末にのみ保存されます。",
      howItWorksTitle: "ゲームの仕組み",
      howItWorksText:
        "表か裏を選び、コインのデザインを決めてトスします。各結果は暗号学的に安全な50/50の公正な乱数生成によって計算されます。",
    },
    scoreboard: {
      flips: "総トス数",
      wins: "勝利数",
      losses: "敗北数",
      winRate: "勝率",
      bestStreak: "最高連勝",
    },
    history: {
      title: "最近のトス履歴",
      empty: "ここにトス履歴が表示されます — コインを投げてみましょう！",
      guestPrompt: "サインインして連勝記録を保存し、最近のトス履歴を表示しましょう。",
      winBadge: "勝利",
      lossBadge: "敗北",
      called: "選択",
      landed: "結果",
    },
    coins: {
      quarter: "米クォーター硬貨",
      uk10p: "英10ペンス硬貨",
      rupee: "インドルピー硬貨",
      dirham: "UAEディルハム硬貨",
      penny: "米ペニー硬貨",
    },
    blog: {
      backToGame: "ゲームに戻る",
      title: "コイントスの科学と歴史ブログ",
      subtitle: "確率論、決断の心理学、そして2,000年にわたるコイントスの歴史。",
      readTime: "分で読める",
      takeaway: "重要ポイント",
      article1Tag: "数学と確率論",
      article1Title: "コイントスは本当に50/50か？回転の科学",
      article1P1: "何世紀にもわたり、人々はコインの裏表で決断を下してきました。しかし数学的には完全に50.000%公正なのでしょうか？",
      article1P2: "スタンフォード大学の研究では、現実のコインにはわずか50.8%の物理的偏りがあることが判明しました。",
      article1P3: "当アプリのデジタルエンジンはCSPRNG（暗号論的擬似乱数生成器）を採用し、完全な50.000%の公平性を実現しています。",
      article1Takeaway: "デジタル乱数により、物理的な偏りのない純粋な50.000%の確率を提供します。",
      article2Tag: "心理学と意思決定",
      article2Title: "決断疲れ？賢いリーダーがコイントスを使う理由",
      article2P1: "大人は1日に約35,000回の決断を下しており、これが決断疲れを引き起こします。",
      article2P2: "コインが空中にある瞬間、あなたの潜在意識はどちらの結果を本当に望んでいるかを直感的に悟ります。",
      article2P3: "2つの選択肢で迷ったときはコインを投げ、空中で感じる直感に耳を傾けてみましょう。",
      article2Takeaway: "コイントスは、回転している間にあなたの本当の望みを浮き彫りにします。",
      article3Tag: "歴史と文化",
      article3Title: "カエサルからスーパーボウルまで：表と裏の歴史",
      article3P1: "古代ローマでは「船か頭か」（Navia aut Caput）と呼ばれ、皇帝の肖像が刻まれていました。",
      article3P2: "ローマの裁判官は神聖な判断としてカエサルのコインを投げて裁定を下しました。",
      article3P3: "今日でもスーパーボウルの開始トスなど、世界的な舞台で伝統が受け継がれています。",
      article3Takeaway: "2,000年以上にわたり、コインは公平な運命の審判者であり続けています。",
    },
    faq: {
      title: "よくある質問 (FAQ)",
      subtitle: "確率の公平性、暗号乱数、アカウント機能についてのQ&A。",
      backToGame: "ゲームに戻る",
      q1: "このコイントスは本当に公平（50/50）ですか？",
      a1: "はい！Node.jsのCSPRNG（暗号論的擬似乱数生成器）を使用し、完全に偏りのない50.000%の確率を実現しています。",
      q2: "MongoDB Atlasでデータはどのように保存されますか？",
      a2: "サインインすると、スコアや連勝記録が安全なクラウドに保存されます。パスワードはbcryptjsで暗号化されます。",
      q3: "現実のコインに50.8%の偏りがあるのはなぜですか？",
      a3: "物理的なコインは回転時にわずかなブレが生じます。当アプリのデジタル抽選は物理的偏りが一切ありません。",
      q4: "オフラインでもプレイできますか？",
      a4: "はい！ネット接続が切れた場合も自動的にブラウザ内のオフラインモードに切り替わります。",
      q5: "言語の切り替え方法は？",
      a5: "ナビゲーションバーの言語メニューからいつでも7言語に切り替え可能です。",
    },
    coinHistory: {
      title: "コイントス 2,000年の歴史",
      subtitle: "古代ローマ皇帝からライト兄弟、スーパーボウルまでの歴史的物語。",
      backToGame: "ゲームに戻る",
      era1Badge: "古代ローマ (~紀元前44年)",
      era1Title: "船か頭か (Navia aut Caput)",
      era1P: "古代ローマでは皇帝の肖像と軍艦の船首が刻まれたコインを投げ、神聖な裁判の裁定に用いました。",
      era2Badge: "中世ヨーロッパ (~1300年代)",
      era2Title: "十字と刻印 (Cross and Pile)",
      era2P: "中世では表にキリスト教の十字架、裏にコイン鋳造時の刻印が施されていました。",
      era3Badge: "航空史 (1903年)",
      era3Title: "ライト兄弟の運命のトス",
      era3P: "ライト兄弟は人類初の動力飛行のパイロットを決めるためにコイントスを行いました。",
      era4Badge: "アメリカ史 (1845年)",
      era4Title: "ポートランドの命名",
      era4P: "開拓者たちが街の命名をかけ、銅貨を3回投げてポートランドと名付けました。",
      era5Badge: "現代 (現在)",
      era5Title: "スーパーボウルと世界スポーツ",
      era5P: "現在でもクリケットやNFLスーパーボウルの公式開幕儀式として受け継がれています。",
    },
    legal: {
      termsTitle: "利用規約 (Terms & Conditions)",
      termsSubtitle: "Heads or Tails サービスの利用条件。",
      privacyTitle: "プライバシーポリシー (Privacy Policy)",
      privacySubtitle: "MongoDB Atlas による安全なデータ管理について。",
      backToGame: "ゲームに戻る",
      lastUpdated: "最終更新日: 2026年8月",
      termsSec1Title: "1. 規約への同意",
      termsSec1Text: "本サービスを利用することにより、利用規約に同意したものとみなされます。娯楽目的で提供されます。",
      termsSec2Title: "2. ギャンブルの禁止",
      termsSec2Text: "本アプリは無料シミュレーションであり、現実の金銭の賭けは一切行えません。",
      termsSec3Title: "3. 暗号学的な公平性",
      termsSec3Text: "すべての結果はCSPRNGによって公平に計算され、改ざんはありません。",
      termsSec4Title: "4. アカウントセキュリティ",
      termsSec4Text: "パスワードは暗号化ハッシュ化（bcrypt）されて安全に保存されます。",
      privacySec1Title: "1. 収集する情報",
      privacySec1Text: "氏名、メールアドレス、ゲーム成績を収集し、スコアの同期に使用します。",
      privacySec2Title: "2. MongoDB Atlas の安全性",
      privacySec2Text: "データはTLS/SSLおよびAES-256で暗号化された安全なクラウドに保管されます。",
      privacySec3Title: "3. ローカルストレージ",
      privacySec3Text: "セッションと選択言語の維持にのみlocalStorageを使用します。",
      privacySec4Title: "4. データの第三者非提供",
      privacySec4Text: "個人情報を第三者に販売・提供することは決してありません。",
    },
    auth: {
      loginTitle: "おかえりなさい",
      loginSubtitle: "ログインして記録と連勝データを同期しましょう。",
      signupTitle: "アカウント作成",
      signupSubtitle: "記録を保存し、カスタムコインをアンロックしましょう。",
      nameLabel: "お名前",
      namePlaceholder: "例: 山田 太郎",
      emailLabel: "メールアドレス",
      emailPlaceholder: "name@example.com",
      passwordLabel: "パスワード",
      passwordPlaceholder: "6文字以上",
      loginSubmit: "ログイン",
      signupSubmit: "アカウント作成",
      noAccount: "アカウントをお持ちでないですか？",
      hasAccount: "すでにアカウントをお持ちですか？",
      switchSignup: "新規登録",
      switchLogin: "ログイン",
      loggingIn: "ログイン中...",
      signingUp: "作成中...",
    },
    footer: {
      aboutTitle: "表か裏か (Heads or Tails) オンライン",
      aboutText: "3D物理シミュレーション、暗号論的公正乱数、効果音、世界のコインを搭載したコイントスゲーム。",
      quickLinks: "クイックナビゲーション",
      playGame: "コイントスをプレイ",
      blog: "ブログと確率論",
      faq: "よくある質問 (FAQ)",
      history: "コイントスの歴史",
      legal: "法的情報と規約",
      terms: "利用規約",
      privacy: "プライバシーポリシー",
      features: "機能紹介",
      fairRng: "100%公平なCSPRNG",
      soundEffects: "リアルな3D効果音",
      globalCoins: "世界各国のコイン",
      statsTracker: "リアルタイム統計",
      statusOnline: "API & Atlas 稼働中",
      socialTitle: "ソーシャル・コミュニティ",
      disclaimer: "娯楽および意思決定の補助を目的としています — ギャンブルや金銭は一切関係ありません。",
      copyright: "Heads or Tails. 無断転載を禁じます。",
      backToTop: "ページ上部へ",
    },
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    const saved = localStorage.getItem("coin_app_lang");
    if (saved && TRANSLATIONS[saved]) return saved;
    const browserLang = navigator.language?.slice(0, 2);
    return TRANSLATIONS[browserLang] ? browserLang : "en";
  });

  useEffect(() => {
    localStorage.setItem("coin_app_lang", currentLang);
    document.documentElement.lang = currentLang;
  }, [currentLang]);

  const activeLanguageObj = LANGUAGES.find((l) => l.code === currentLang) || LANGUAGES[0];

  const t = (section, key, fallback = "") => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS.en;
    if (section && key) {
      const val = langDict[section]?.[key] ?? TRANSLATIONS.en[section]?.[key];
      return val !== undefined ? val : fallback || key;
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLang,
        setLanguage: setCurrentLang,
        languages: LANGUAGES,
        activeLanguage: activeLanguageObj,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
